language: python
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # are not specific to using mini
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    - sudo apt-get install r-base r-base-dev
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in test.synapseConfig.enc -out test.synapseConfig -d; mv test.synapseConfig ~/.synapseConfig; fi'



install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib nose pandas coverage scikit-learn
  # coverage packages are elsewhere
  #- conda install --yes -c python-coveralls nose-cov
  - pip install nose easydev --upgrade
  - pip install coveralls
  - pip install biokit fitter
  - pip install git+https://git@github.com/cokelaer/synapsePythonClient.git@v1.4.0_py3_dreamtools#egg=synapsePythonClient

# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package dreamtools

after_success:
  coveralls
